2021-01-06 11:07:46,294 D:/python/pythonWorkSpace/quant/test4.py(10): ERROR error:
2021-01-06 11:07:46,294 D:/python/pythonWorkSpace/quant/test4.py(11): ERROR (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x0000024CE21A1AC0>)
Traceback (most recent call last):
  File "D:/python/pythonWorkSpace/quant/test4.py", line 8, in <module>
    print(1 / 0)
ZeroDivisionError: division by zero
2021-01-06 11:10:03,466 D:/python/pythonWorkSpace/quant/test4.py(10): ERROR error:
2021-01-06 11:10:03,466 D:/python/pythonWorkSpace/quant/test4.py(11): ERROR (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x000002078FBF1900>)
Traceback (most recent call last):
  File "D:/python/pythonWorkSpace/quant/test4.py", line 8, in <module>
    print(1 / 0)
ZeroDivisionError: division by zero
2021-01-06 11:11:18,600 - test4.<module>[line:10] - ERROR: error:
2021-01-06 11:11:18,600 - test4.<module>[line:11] - ERROR: (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x0000026222401740>)
Traceback (most recent call last):
  File "D:/python/pythonWorkSpace/quant/test4.py", line 8, in <module>
    print(1 / 0)
ZeroDivisionError: division by zero
2021-01-06 11:11:48,467 - test4.<module>[line:10] - ERROR: error:
2021-01-06 11:11:48,467 - test4.<module>[line:11] - ERROR: (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x0000017830E118C0>)
Traceback (most recent call last):
  File "D:/python/pythonWorkSpace/quant/test4.py", line 8, in <module>
    print(1 / 0)
ZeroDivisionError: division by zero
2021-01-06 11:12:24,306 - test4.func[line:10] - ERROR: error:
2021-01-06 11:12:24,306 - test4.func[line:11] - ERROR: (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x000001E908ED08C0>)
Traceback (most recent call last):
  File "D:/python/pythonWorkSpace/quant/test4.py", line 8, in func
    print(1 / 0)
ZeroDivisionError: division by zero
2021-01-06 11:14:03,572 - test4.func[line:10] - ERROR: error:
2021-01-06 11:14:03,573 - test4.func[line:11] - ERROR: (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x0000024737B208C0>)
Traceback (most recent call last):
  File "D:/python/pythonWorkSpace/quant/test4.py", line 8, in func
    print(1 / 0)
ZeroDivisionError: division by zero
2021-01-06 11:17:43,935 - test4.test[line:10] - ERROR: error:
2021-01-06 11:17:43,935 - test4.test[line:11] - ERROR: (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x000002799DD8D580>)
Traceback (most recent call last):
  File "D:/python/pythonWorkSpace/quant/test4.py", line 8, in test
    print(1 / 0)
ZeroDivisionError: division by zero
2021-01-06 11:17:56,410 - test4.test[line:10] - ERROR: error:
2021-01-06 11:17:57,361 - test4.test[line:11] - ERROR: (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x00000199BED53440>)
Traceback (most recent call last):
  File "D:/python/pythonWorkSpace/quant/test4.py", line 8, in test
    print(1 / 0)
ZeroDivisionError: division by zero
2021-01-06 11:19:12,269 - test4.test[line:10] - ERROR: error:
2021-01-06 11:19:12,269 - test4.test[line:11] - ERROR: (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x000001BEBFFD0A40>)
Traceback (most recent call last):
  File "D:/python/pythonWorkSpace/quant/test4.py", line 8, in test
    print(1 / 0)
ZeroDivisionError: division by zero
2021-01-06 11:20:08,120 - test4.test[line:10] - ERROR: error:
2021-01-06 11:20:08,120 - test4.test[line:11] - ERROR: (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x000001241FBBD5C0>)
Traceback (most recent call last):
  File "D:/python/pythonWorkSpace/quant/test4.py", line 8, in test
    print(1 / 0)
ZeroDivisionError: division by zero
